server:
  port: 2002
spring:
  application:
    # Application Name
    name: OAUTH2-SERVICE
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ## Should be added or find it COG Auth
            clientSecret: ## Should be added or find it COG Auth
            scope:
              - email
              - profile
          facebook:
            clientId: ## Should be added or find it COG Auth
            clientSecret: ## Should be added or find it COG Auth
            scope:
              - email
              - public_profile
              - user_hometown
              - user_location
              - attribution_read
          apple:
            clientId: com.cloudofgood.consumer
            clientSecret: ## Should be added or find it COG Auth
            authorizationGrantType: authorization_code
#            redirectUri: 'http://localhost:2002/login'
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - openid
              - name
              - email
            clientName: Apple
            clientAuthenticationMethod: post
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
#   DATABASE CONFIGURATIONS
  datasource:
    url: ## Should be added or find it COG Auth
    username: ## Should be added or find it COG Auth
    password: ## Should be added or find it COG Auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
